### ISSUE TITLE
AUTOSAVE files created in current file directory instead of .local-histor folder

### ISSUE THREAD

**Issue by zoomido** [mg979/vim-localhistory#2]
I've noticed recently (as in after vacation) that AUTOSAVE files are created in the same directory as the file. I don't remember seeing these before here so I don't know if maybe the AUTOSAVE feature don't respect the local-history folder anymore?
I have already tried setting the `let g:lh_basedir = '~/.local_history'` outright but it doesn't make any difference.

**Comment by mg979** [comment]
Thanks for reporting, it should be fixed, I rewrote the plugin recently and I didn't test autosave. Maybe I should remove this feature anyway because it saves too many files.
